### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mathieutu** [itsDamien/laravel-heroku-config-parser#2]
FYI, the putenv method is not usable anymore in runtime: 
https://github.com/laravel/framework/issues/27695
https://github.com/laravel/docs/pull/5039

I'm trying to find a better solution 😉

**Comment by damiencriado** [comment]
Thanks for the feedback !

BTW there is a proper way to achieve what this package is made for:

At the top of your `database.php`
```
$herokuDatabase = parse_url(env('DATABASE_URL'));
$herokuDatabase['path'] = ltrim($herokuDatabase['path'], '/');
```
```
array:6 [
  "scheme" => "mysql"
  "host" => "ec2-s2"
  "port" => 3306
  "user" => "usr"
  "pass" => "pwd"
  "path" => "db2"
]
```

And then :
```
'mysql' => [
        'driver' => 'mysql',
        'host' => env('DB_HOST', $herokuDatabase['host'] ?? '127.0.0.1'),
        'port' => env('DB_PORT', $herokuDatabase['port'] ?? '3306'),
        'database' => env('DB_DATABASE', $herokuDatabase['path'] ?? 'forge'),
        'username' => env('DB_USERNAME', $herokuDatabase['user'] ?? 'forge'),
        'password' => env('DB_PASSWORD', $herokuDatabase['pass'] ?? ''),
        ...
],
```

Laravel will try to use the value of `DB_HOST` then will fallback with `$herokuDatabase['host']` and then with `127.0.0.1`

**Comment by mathieutu** [comment]
Yeah, it's the non proper way to do it (and the way I did it before), but it doesn't handle the scheme, and the other options.

I'm currently doing a test that will handle completely all the complexity and let you know.

**Comment by damiencriado** [comment]
The scheme can be handled like this
```
$herokuDatabase = parse_url(env('DATABASE_URL'));
$herokuDatabase['connection'] = $herokuDatabase['scheme'] === 'postgres' ? 'pgsql' : $herokuDatabase['scheme'];
$herokuDatabase['database'] = ltrim($herokuDatabase['path'], '/');
```
```
array:8 [
  "scheme" => "postgres"
  "host" => "ec2-s1"
  "port" => 5432
  "user" => "usr"
  "pass" => "pwd"
  "path" => "/db1"
  "connection" => "pgsql"
  "database" => "db1"
]
```
```
'default' => env('DB_CONNECTION', $herokuDatabase['connection'] ?? 'mysql'),
```

Can't wait to see your proposal

**Comment by mathieutu** [comment]
Yeah, but I'm trying to do it with the minimum of manual code / modification required, like you did on this package 😉.

**Comment by damiencriado** [comment]
Effectivement le principe de juste rajouter le paquet où tout est automatique est intéressant mais avec un projet un peu plus complexe qui n’utilise pas `pgsql` ou `mysql` comme nom de connexion ça devient compliqué. À mon avis pour une v2 il ne faut pas overwrite les envs mais juste utiliser une classe/helper dans le fallback du env():
Exemple:
env(‘DB_HOST’, herokuDb(‘host’, ‘127.0.0.1’))

**Comment by damiencriado** [comment]
Anything new ?

**Comment by mathieutu** [comment]
Yeah, I've done something just for my project, but it can be improved. I let you know when it will be ready 😉

**Comment by mathieutu** [comment]
For information, I'm working on a pull request about it:
https://github.com/laravel/framework/pull/28096

**Comment by mathieutu** [comment]
Hi, as laravel/framework#28096 has been merged, you can use directly DATABASE_URL in you config file 🎉, this issue can be closed.

**Comment by damiencriado** [comment]
Cool ! thanks for your work
